# Generated by Django 3.2.12 on 2022-04-05 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case_study_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='my_model',
            new_name='MyDataModel',
        ),
    ]
